language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt --use-mirrors
- cp foiamachine/settings/test.py foiamachine/settings/local.py
script:
- python foiamachine/manage.py test core requests users doccloud agency government mail contacts supporters